# `Numpy`:
Library used for computations and processing of multi-dimensional arrays and matrices.

In [4]:
import numpy as np

Creating an array

In [ ]:
a = np.array([1,2,3])

In [6]:
type(a)

numpy.ndarray

In [7]:
a = np.array([1,2,3],dtype=float)
a

array([1., 2., 3.])

In [8]:
a = np.array([1,2,3], dtype=str)
a

array(['1', '2', '3'], dtype='<U1')

In [9]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
len(a)

2

In [ ]:
a.ndim # it is 2D array

2

In [13]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)
print(b.ndim)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3


### `Why use NUMPY?`
- **Speed**: NumPy is much faster than Python lists for numerical computations. This is because NumPy uses C under the hood, which is a compiled language that is much faster than Python. It is said to be 15-60 times faster than Python lists.
- **Memory Efficiency**: NumPy arrays are more memory efficient than Python lists. This is because NumPy arrays store only the necessary information to represent the array, whereas Python lists store a lot of extra information like the length of the list, the type of each element, etc.
- **Vectorized Operations**: NumPy arrays support vectorized operations, which means that you can perform operations on the entire array at once, rather than having to loop over each element individually. This makes it much easier to perform complex operations on large datasets. 

In [15]:
b.shape

(2, 2, 2)

In [16]:
a.dtype

dtype('int64')

**`Accessing/ Changing specific elements, rwos, cols:`**<br> it is same as accessing/ changing elements in a list. We can access/ change specific elements in a matrix by their row and column index. For example, to access the element at the 2nd row and 3rd column, we use matrix[1][2]. To change the element at the 2nd row and 3rd column, we use matrix[1][2] = 10.

### `Zeros/Ones methods`:
- `zeros()`: Returns a tensor filled with zeros.
- `ones()`: Returns a tensor filled with ones.

In [17]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
np.ones((3,3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [20]:
np.ones((3,3), dtype=str)

array([['1', '1', '1'],
       ['1', '1', '1'],
       ['1', '1', '1']], dtype='<U1')

In [21]:
np.zeros((3,3), dtype=str)

array([['', '', ''],
       ['', '', ''],
       ['', '', '']], dtype='<U1')

In [23]:
np.full((3,3), "Honey")

array([['Honey', 'Honey', 'Honey'],
       ['Honey', 'Honey', 'Honey'],
       ['Honey', 'Honey', 'Honey']], dtype='<U5')

In [29]:
np.random.rand(3,3)

array([[0.84519289, 0.15909014, 0.89472833],
       [0.99503812, 0.2653519 , 0.75340018],
       [0.67807391, 0.94679917, 0.77030172]])

In [48]:
np.random.randint(1,1001, size=(5,5))

array([[741, 665,  96, 710, 906],
       [167,   1, 510, 728, 828],
       [245, 497, 435, 254, 431],
       [107, 936, 864, 854, 911],
       [937,  14, 577,  35, 162]])

In [49]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Extract all the first 3 rows of the last 5 columns in a given numpy 2D array ‘a’?

In [50]:
a= np.array([[51,52,53,54,55,56],
             [10,20,30,40,50,60],
             [12,12,12,12,12,12],
             [11,21,31,41,51,61],
             [13,24,34,44,54,64]])

In [51]:
a[:3,-5:]

array([[52, 53, 54, 55, 56],
       [20, 30, 40, 50, 60],
       [12, 12, 12, 12, 12]])

Given a positive number 'n' greater than 2, create a NumPy array of size (nxn) with all zeros and ones such that the ones make a shape of "+"

In [53]:
n = 5
z = np.zeros((n,n),dtype=int)

In [55]:
x = n // 2

In [57]:
# Make the middle row and column all 1s

z[x,:] = 1
z[:,x] = 1

# Print the final value of z
print(z)

[[0 0 1 0 0]
 [0 0 1 0 0]
 [1 1 1 1 1]
 [0 0 1 0 0]
 [0 0 1 0 0]]


### `Arithmatic Operations with NumPy`
The operatioons are performed on each element of the array. We don't need to use a loop to perform the operations.

In [58]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [59]:
a + 4

array([5, 6, 7, 8])

In [60]:
a ** 3

array([ 1,  8, 27, 64])

In [61]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [62]:
a + b

array([ 6,  8, 10, 12])

In [63]:
a = np.array([1,2,3,4])
b = np.array([5,6])

In [ ]:
a + b # their Shape should be same

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

In [67]:
print(a.min())

1


In [68]:
print(np.min(a))

1


In [70]:
print(a.max())

4


In [73]:
print(a.mean())

2.5


In [74]:
print(np.sum(a))

10


axis in NumPy:<br>
axis 0 = rows<br>
axis 1 = columns<br>

In [78]:
a = np.array([[1,2,3,4],[5,6,7,8]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [80]:
print(np.min(a, axis = 0))

[1 2 3 4]


In [81]:
print(np.min(a, axis = 1))

[1 5]


In [ ]:
print(np.sum(a, axis = 1))

[10 26]


In [84]:
print(np.sum(a, axis = 0))

[ 6  8 10 12]
